### ISSUE TITLE
Metadata update

### ISSUE THREAD

**Issue by reeshmabijosh** [drxyzw/WuhanCoronavirus-Malaysia#1]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data frame http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/OZZXAY
Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by drxyzw** [comment]
Hello,
Sorry I missed your post.
I am happy to keep my data decent.
As for raw data (ex. daily new cases) is automatically updated everyday by GitHub Actions.
As for data related Rt, I am upgrading the computation model.
And the second url does not seem to work. Maybe the ID has expired already.

**Comment by drxyzw** [comment]
I have added information on each csv file on case number analysis in README.md.
For Rt computation, I will write a document.

**Comment by drxyzw** [comment]
I added a document
https://github.com/drxyzw/WuhanCoronavirus-Malaysia/tree/master/doc/Rt-Malaysia.ipynb
